### PR TITLE
Added support for an option to retain buffer instead of converting to String on 'line' event

### PR DESCRIPTION
**Pull request by esaounkine**
Covered with test and added documentation. Also reformatted the code to make it more readable.

### CODE REVIEW

**Comment by maleck13** [comment]
@esaounkine  thanks for your pull request. It looks fine from scanning the code. I will try it out locally. If all good I will merge and publish the change

**Comment by esaounkine** [comment]
Good plan! 
Will be awesome to get rid of my fork used in a project where I needed this functionality ;)

**Comment by maleck13** [comment]
@esaounkine published @1.3.0

**Comment by esaounkine** [comment]
Great news! Thanks!

**Pull request merged**
