### PR TITLE
Streams.

### PR DESCRIPTION
**Pull request by ibakaidov**
I need read from stdin linebyline, and i wanna use this module, but see what you haven't this option. I add this.

### CODE REVIEW

**Comment by maleck13** [comment]
thanks for your pull request. I will take a look and hopefully merge today

**Comment by ibakaidov** [comment]
and?

**Comment by dkavassy** [comment]
I'd be interested in this too

**Comment by maleck13** [comment]
@ibakaidov @dkavassy  merged and published

**Comment by dkavassy** [comment]
Thanks, @maleck13

**Pull request merged**
